version: '3.9'

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - mi-red
    restart: always  

networks:
  mi-red:
    driver: bridge
